### ISSUE TITLE
Assertion error in transfer.py

### ISSUE THREAD

**Issue by Rukhmini** [arpanmangal/CovidAID#1]
I am getting assertion error in transfer.py code in line no:46 
assert len(c_keys.difference(t_keys)) == 0
The error is:
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
~\CovidAID-master\tools\transfer.py in <module>
     44 #print (len(c_keys.difference(t_keys)))
     45 #print (len(t_keys.difference(c_keys)))
---> 46 assert len(c_keys.difference(t_keys)) == 0
     47 assert len(t_keys.difference(c_keys)) == 0
     48 

AssertionError:

**Comment by arpanmangal** [comment]
Please report your `pytorch` and `torchvision` versions. If not already doing, use the correct version of these packages as mentioned here: https://github.com/arpanmangal/CovidAID/blob/master/INSTALL.md

**Comment by bartmch** [comment]
I'm currently trying to update your repo to support torch1.5. The versions you're using support cuda80, I'm on cuda10.2 so that will not work.
I have 2 questions:
1. The assertion mentioned by @Rukhmini compartes a torch.models.densenet121 model architecture with the pre-trained chexnet model from another repo. The imported densenet121 is on torch1.5. This makes me assume that the chexnet model is causing issues and will need to be updated to be supported by torch1.5, is that correct?
2. What other changes do you anticipate for running it on torch1.5?

**Comment by arpanmangal** [comment]
@bartmch 
1. Yes, the main reason for using the older `torch` version is compatibility with the pre-trained CheXNet model. It is possible to change the CheXNet model in the latest format. `pytorch0.3` and `pytorch>=1.0` models differ mainly in the names of `keys` in the `state_dict` of the model, and maintaining some running variables for batch norm. One will have to load the old trained model and transfer it's trained weights in the newer format.
2. Other changes one will have to do is to change the forward pass code in `tools/trainer.py` as well as `tools/inference.py`, removing the `autograd.Variable` instances which have been depreciated since `pytorch0.4`

**Comment by bartmch** [comment]
Thanks for the quick reply! @arpanmangal on point (1):
I successfully changed the state_dict keys, what do I do for the num_batches_tracked layers? Do I ignore the following assertion in "transfer.py"? (as it's a torch(0) layer)

![image](https://user-images.githubusercontent.com/10415569/81811266-6ba4f700-9535-11ea-8814-e79c21c7dc08.png)

If it's not clear, I'm talking about the "num_batches_tracked" layers available on torch>1.0 but not in torch<1.0

![image](https://user-images.githubusercontent.com/10415569/81811208-529c4600-9535-11ea-9e66-e19d3dbe7798.png)

**Comment by bartmch** [comment]
I was thinking about this solution because num_batches_tracked are 0 tensors (removed the commented line):
![image](https://user-images.githubusercontent.com/10415569/81812224-e9b5cd80-9536-11ea-92be-728904a327d6.png)
Would that solve the problem you think?

**Comment by arpanmangal** [comment]
@bartmch Continuing the discussion in #2

**Comment by Rukhmini** [comment]
@bartmch Have you successfully run the code using pytorch>1.0. If so, can you please guide what are the changes required to run the code successfully?

**Comment by bartmch** [comment]
> @bartmch Have you successfully run the code using pytorch>1.0. If so, can you please guide what are the changes required to run the code successfully?

See previous messages. In short implement the following snippet to make the layers compatible:
`    for key in list(state_dict.keys()):
        res = pattern.match(key)
        if res:
            new_key = res.group(1) + res.group(2)
            state_dict[new_key] = state_dict[key]
            del state_dict[key]`

**Comment by shroq1** [comment]
@bartmch what did you mean of res = pattern.match(key)"?
